on:
  pull_request_review:
    types:
      - submitted

jobs:
  lgtm:
    name: LGTM
    runs-on: ubuntu-latest
    steps:
    - name: Setup approved-event
      uses: taichi/approved-event-action@v1.2.1
      id: approved
      with:
        approvals: '1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cowsay LGTM
      uses: Code-Hex/neo-cowsay-action@v1.0.1
      if: steps.approved.outputs.approved == 'true'
      with:
        message: 'LGTM'
        cow: 'random'
        cowsay_on_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}